
server:
  port: 7070

spring:
  application:
    name: department-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/departmentDb?createDatabaseIfNotExist=true
    username: root
    password: boss
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.employee.departmentservice: TRACE

eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka/