
server:
  port: 7070

spring:
  application:
    name: employee-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/departmentDb?createDatabaseIfNotExist=true
    username: root
    password: boss
    driverClassName: com.mysql.cj.jdbc.Driver

  data:
    jpa:
      repositories:
        enabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.employee.departmentservice: TRACE
